### ISSUE TITLE
Anotaciones

### ISSUE THREAD

**Issue by ivanjimenez** [danieldat/Pokemon#1]
Hola, Daniel:

 Bien, en primer lugar, buen trabajo. 

 En primer lugar tienes código duplicado en Juego.java, puedes incluirlo en una función y ahorras líneas de código.

 Luego el try/catch al capturar el error del nexInt luego en el catch asignas una asignación a la variable op. Las excepciones capturan los errores para que no se corte la ejecución del programa. Supongo que el for son las tiradas (no conozco mucho a los pokemons :-) ).  Tal y como está el código si no se captura la variable op entraría en un bucle pero al poner op = 3, utilizas un valor por defecto. Deberías controlar que sale alguna excepción con una variable booleana y dar alguna opción más. 

Tal vez deberías separar la captura de la variable op del resto del código probando lo anterior.

**Comment by danieldat** [comment]
Buenos días:

Por lo de ahorrar código,lo acabo de hacer, que no sabia bien como
hacerlo.Hice una función y ha quedado perfecto.Gracias

Esto es un programa juego que me estoy inventando,con el tema pokemon,me es
mas fácil determinar las clases y me lo hace mas divertido  jajajaja,pero
es solo una temática,no se parece mucho al juego original.


La cosa es que cuando elijas una opción solo pueda ser 1,2 o 3, eso lo
resolví.Pero  si se  pone alguna letra o símbolo,en vez de que de error el
Scanner,quiero que te de un mensaje y puedas volver a introducir una de
estas 3 opciones y esto se introduce 3 veces.(para que se te asignen
aleatoriamente 3 pokemons).Si metes bien los números no hay problema.

-Puse el op=3 para ver si ahí me daba error o no.
-Puse también i--,para que me diera una nueva oportunidad,pero se quedó
repitiéndose en bucle,pues no me volvía a dar opción para modificar op en
un nuevo intento

Lo que has dicho del booleano no lo entiendo muy bien.

**Comment by danieldat** [comment]
Mira este es el ejercicio 1 de las exceptions del tema 8.En este me pasa lo
mismo que en el otro,que si meto una letra el valor introducido se queda
fijo,y ahora siempre es el mismo.No me vuelve a dar a elegir y poner otro
numero.




package Ejercicios;
import java.util.Scanner;
/**
 *
 * @author alumnot
 */
public class Ejercicio1 {
    public static void main (String [] args){

    Scanner sc=new Scanner(System.in);

    int mayor=0;
    System.out.println("Introduce 6 numeros y te digo cual es el mayor");
    int[] e=new int[6];

    for(int i=0;i<6;i++){
    System.out.println("Llevas"+i);
    try{
    e[i]=sc.nextInt();
    }catch(Exception ae){System.out.println("Fallo");}
    }


    for(int u=0;u<6;u++){
    if(mayor<e[u]){mayor=e[u];}


    }
    System.out.print("El mayor es "+mayor);




    }

}

**Comment by ivanjimenez** [comment]
Daniel, antes de nada, por si te puede servir. He puesto un par de vídeos explicando las excepciones por si te pueden servir y cuando los visiones, si no ves la solución, lo revisamos. Mira antes los videos en el grupo de Programación del github

**Comment by danieldat** [comment]
Buenas tardes:

Ya he dado con la solución!!!
El problema de que en la introducción del dato, se me guardara, y en bucle
me saliera todo el rato la opción errónea que puse al principio,es porque
estaba usando un INT como dato,al usar un double funciona perfectamente
como tu muestras en el ejemplo.Será algún bug que tenga el java supongo.




<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ivanjimenez** [comment]
Cierro esta issue Daniel proque ya está solucionada por tu parte
